# Generated by Django 3.2.3 on 2021-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
